/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLLFileSearchManager;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Christian
 */
public class WordSearch extends javax.swing.JFrame 
{
    private BLLFileSearchManager fsmgr;
    private DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form WordSearch
     */
    public WordSearch() {
        try {
            fsmgr = new BLLFileSearchManager();
        }
        catch (FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, "Kunne ikke læse filen", "Fejl", JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        setLocationRelativeTo(null);
        listResult.setModel(model); 
        try
        {
            //Henter ordene ind fra FileSearchManageren
            for(Object word : fsmgr.getWords()){ 
                model.addElement(word.toString()); //skriver ordene i Jlisten. 
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(WordSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
        rdbtnBeginsWith.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btngrpSearchType = new javax.swing.ButtonGroup();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtQuery = new javax.swing.JTextField();
        lblQuery = new javax.swing.JLabel();
        lblResults = new javax.swing.JLabel();
        jpnlSearchType = new javax.swing.JPanel();
        rdbtnBeginsWith = new javax.swing.JRadioButton();
        rdbtnContains = new javax.swing.JRadioButton();
        rdbtnEndsWith = new javax.swing.JRadioButton();
        rdbtnExact = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        checkboxCaseSensitive = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        comboboxLimitations = new javax.swing.JComboBox();
        lblCount = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        scrpResult = new javax.swing.JScrollPane();
        listResult = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setText("Søg");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setText("Ryd");
        btnClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearActionPerformed(evt);
            }
        });

        txtQuery.setText("Skriv tekst her");
        txtQuery.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtQueryActionPerformed(evt);
            }
        });

        lblQuery.setText("Søgning:");

        lblResults.setText("Resultater:");

        jpnlSearchType.setBorder(javax.swing.BorderFactory.createTitledBorder("Søge type"));

        btngrpSearchType.add(rdbtnBeginsWith);
        rdbtnBeginsWith.setText("Starter med");

        btngrpSearchType.add(rdbtnContains);
        rdbtnContains.setText("Indeholder");

        btngrpSearchType.add(rdbtnEndsWith);
        rdbtnEndsWith.setText("Slutter med");

        btngrpSearchType.add(rdbtnExact);
        rdbtnExact.setText("Præcis");

        javax.swing.GroupLayout jpnlSearchTypeLayout = new javax.swing.GroupLayout(jpnlSearchType);
        jpnlSearchType.setLayout(jpnlSearchTypeLayout);
        jpnlSearchTypeLayout.setHorizontalGroup(
            jpnlSearchTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSearchTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlSearchTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnBeginsWith)
                    .addComponent(rdbtnContains)
                    .addComponent(rdbtnEndsWith)
                    .addComponent(rdbtnExact))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlSearchTypeLayout.setVerticalGroup(
            jpnlSearchTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSearchTypeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbtnBeginsWith)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnContains)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnEndsWith)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnExact))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Style"));

        checkboxCaseSensitive.setText("Form følsom");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxCaseSensitive)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkboxCaseSensitive)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Begrænsning"));

        comboboxLimitations.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "50\t", "100" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboboxLimitations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboboxLimitations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCount.setText("Mulige:");

        btnClose.setText("Luk");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        scrpResult.setViewportView(listResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuery)
                    .addComponent(lblResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuery, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCount)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrpResult, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jpnlSearchType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnClose))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnClear)
                    .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuery))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResults)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jpnlSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrpResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCount)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueryActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (rdbtnBeginsWith.isSelected() == true){
            model.clear();
            try {
                for (Object search : fsmgr.beginsWith(txtQuery.getText())) {
                    model.addElement(search);
                }
                lblCount.setText("Mulige: " + fsmgr.beginsWith(txtQuery.getText()).size());
            }
            catch (Exception ex)
            {
                Logger.getLogger(WordSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (rdbtnEndsWith.isSelected() == true) {
            model.clear();
            try {
                for (Object search : fsmgr.endsWith(txtQuery.getText())) {
                    model.addElement(search);
                }
                lblCount.setText("Mulige: " + fsmgr.endsWith(txtQuery.getText()).size());
            }
            catch (Exception ex)
            {
                Logger.getLogger(WordSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (rdbtnContains.isSelected() == true) {
            model.clear();
            try {
                for (Object search : fsmgr.containsWith(txtQuery.getText())) {
                    model.addElement(search);
                }
                lblCount.setText("Mulige: " + fsmgr.endsWith(txtQuery.getText()).size());
            }
            catch (Exception ex)
            {
                Logger.getLogger(WordSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (rdbtnExact.isSelected() == true) {
            model.clear();
            try {
                for (Object search : fsmgr.exactWith(txtQuery.getText())) {
                    model.addElement(search);
                }
                lblCount.setText("Mulige: " + fsmgr.exactWith(txtQuery.getText()).size());
            }
            catch (Exception ex)
            {
                Logger.getLogger(WordSearch.class.getName()).log(Level.SEVERE, null, ex);  
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtQuery.setText("");
        model.clear();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordSearch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup btngrpSearchType;
    private javax.swing.JCheckBox checkboxCaseSensitive;
    private javax.swing.JComboBox comboboxLimitations;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpnlSearchType;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblQuery;
    private javax.swing.JLabel lblResults;
    private javax.swing.JList listResult;
    private javax.swing.JRadioButton rdbtnBeginsWith;
    private javax.swing.JRadioButton rdbtnContains;
    private javax.swing.JRadioButton rdbtnEndsWith;
    private javax.swing.JRadioButton rdbtnExact;
    private javax.swing.JScrollPane scrpResult;
    private javax.swing.JTextField txtQuery;
    // End of variables declaration//GEN-END:variables
}
